# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_front_end.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(460, 460)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(460, 460))
        MainWindow.setMaximumSize(QtCore.QSize(460, 460))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2a1a1f;\n"
"    color: #f5e9e2;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 431, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.servo_flags_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.servo_flags_button.sizePolicy().hasHeightForWidth())
        self.servo_flags_button.setSizePolicy(sizePolicy)
        self.servo_flags_button.setMaximumSize(QtCore.QSize(220, 40))
        self.servo_flags_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.servo_flags_button.setObjectName("servo_flags_button")
        self.horizontalLayout_3.addWidget(self.servo_flags_button)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_17.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.servo_ready_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.servo_ready_label.setMaximumSize(QtCore.QSize(20, 20))
        self.servo_ready_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.servo_ready_label.setText("")
        self.servo_ready_label.setObjectName("servo_ready_label")
        self.horizontalLayout_4.addWidget(self.servo_ready_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.power_supply_status_label_ = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_supply_status_label_.sizePolicy().hasHeightForWidth())
        self.power_supply_status_label_.setSizePolicy(sizePolicy)
        self.power_supply_status_label_.setMaximumSize(QtCore.QSize(16777215, 20))
        self.power_supply_status_label_.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.power_supply_status_label_.setObjectName("power_supply_status_label_")
        self.horizontalLayout_2.addWidget(self.power_supply_status_label_)
        self.power_supply_status_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.power_supply_status_label.setMaximumSize(QtCore.QSize(20, 20))
        self.power_supply_status_label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.power_supply_status_label.setText("")
        self.power_supply_status_label.setObjectName("power_supply_status_label")
        self.horizontalLayout_2.addWidget(self.power_supply_status_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.power_supply_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.power_supply_button.sizePolicy().hasHeightForWidth())
        self.power_supply_button.setSizePolicy(sizePolicy)
        self.power_supply_button.setMaximumSize(QtCore.QSize(220, 40))
        self.power_supply_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.power_supply_button.setObjectName("power_supply_button")
        self.horizontalLayout_5.addWidget(self.power_supply_button)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.positive_power_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.positive_power_label.sizePolicy().hasHeightForWidth())
        self.positive_power_label.setSizePolicy(sizePolicy)
        self.positive_power_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.positive_power_label.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.positive_power_label.setObjectName("positive_power_label")
        self.verticalLayout_7.addWidget(self.positive_power_label)
        self.negative_power_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.negative_power_label.sizePolicy().hasHeightForWidth())
        self.negative_power_label.setSizePolicy(sizePolicy)
        self.negative_power_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.negative_power_label.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.negative_power_label.setObjectName("negative_power_label")
        self.verticalLayout_7.addWidget(self.negative_power_label)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.read_tuning_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_tuning_button.sizePolicy().hasHeightForWidth())
        self.read_tuning_button.setSizePolicy(sizePolicy)
        self.read_tuning_button.setMaximumSize(QtCore.QSize(220, 40))
        self.read_tuning_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.read_tuning_button.setObjectName("read_tuning_button")
        self.horizontalLayout.addWidget(self.read_tuning_button)
        self.tuning_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuning_label.sizePolicy().hasHeightForWidth())
        self.tuning_label.setSizePolicy(sizePolicy)
        self.tuning_label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tuning_label.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.tuning_label.setObjectName("tuning_label")
        self.horizontalLayout.addWidget(self.tuning_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.activate_tunning_number = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activate_tunning_number.sizePolicy().hasHeightForWidth())
        self.activate_tunning_number.setSizePolicy(sizePolicy)
        self.activate_tunning_number.setMinimumSize(QtCore.QSize(114, 0))
        self.activate_tunning_number.setMaximumSize(QtCore.QSize(220, 40))
        self.activate_tunning_number.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.activate_tunning_number.setObjectName("activate_tunning_number")
        self.horizontalLayout_6.addWidget(self.activate_tunning_number)
        self.write_tuning_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_tuning_spinBox.sizePolicy().hasHeightForWidth())
        self.write_tuning_spinBox.setSizePolicy(sizePolicy)
        self.write_tuning_spinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.write_tuning_spinBox.setStyleSheet("QSpinBox, QDoubleSpinBox {\n"
"    background-color: #3d2a2e;\n"
"    border: 1px solid #5a232a;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    min-width: 80px;\n"
"    color: #f5e9e2;\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #d4a373;\n"
"}\n"
"\n"
"\n"
"")
        self.write_tuning_spinBox.setMinimum(1)
        self.write_tuning_spinBox.setMaximum(4)
        self.write_tuning_spinBox.setObjectName("write_tuning_spinBox")
        self.horizontalLayout_6.addWidget(self.write_tuning_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.write_function_generator_frequency_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_function_generator_frequency_button.sizePolicy().hasHeightForWidth())
        self.write_function_generator_frequency_button.setSizePolicy(sizePolicy)
        self.write_function_generator_frequency_button.setMinimumSize(QtCore.QSize(114, 0))
        self.write_function_generator_frequency_button.setMaximumSize(QtCore.QSize(220, 40))
        self.write_function_generator_frequency_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.write_function_generator_frequency_button.setObjectName("write_function_generator_frequency_button")
        self.horizontalLayout_7.addWidget(self.write_function_generator_frequency_button)
        self.generator_frequency_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_frequency_spinBox.sizePolicy().hasHeightForWidth())
        self.generator_frequency_spinBox.setSizePolicy(sizePolicy)
        self.generator_frequency_spinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.generator_frequency_spinBox.setStyleSheet("QSpinBox, QDoubleSpinBox {\n"
"    background-color: #3d2a2e;\n"
"    border: 1px solid #5a232a;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    min-width: 80px;\n"
"    color: #f5e9e2;\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #d4a373;\n"
"}\n"
"\n"
"\n"
"")
        self.generator_frequency_spinBox.setMinimum(1)
        self.generator_frequency_spinBox.setMaximum(1600)
        self.generator_frequency_spinBox.setSingleStep(10)
        self.generator_frequency_spinBox.setProperty("value", 10)
        self.generator_frequency_spinBox.setObjectName("generator_frequency_spinBox")
        self.horizontalLayout_7.addWidget(self.generator_frequency_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.write_function_generator_amplitude_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.write_function_generator_amplitude_button.sizePolicy().hasHeightForWidth())
        self.write_function_generator_amplitude_button.setSizePolicy(sizePolicy)
        self.write_function_generator_amplitude_button.setMaximumSize(QtCore.QSize(220, 40))
        self.write_function_generator_amplitude_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.write_function_generator_amplitude_button.setObjectName("write_function_generator_amplitude_button")
        self.horizontalLayout_8.addWidget(self.write_function_generator_amplitude_button)
        self.generator_amplitude_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_amplitude_spinBox.sizePolicy().hasHeightForWidth())
        self.generator_amplitude_spinBox.setSizePolicy(sizePolicy)
        self.generator_amplitude_spinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.generator_amplitude_spinBox.setStyleSheet("QSpinBox, QDoubleSpinBox {\n"
"    background-color: #3d2a2e;\n"
"    border: 1px solid #5a232a;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    min-width: 80px;\n"
"    color: #f5e9e2;\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #d4a373;\n"
"}\n"
"\n"
"")
        self.generator_amplitude_spinBox.setMaximum(4000)
        self.generator_amplitude_spinBox.setObjectName("generator_amplitude_spinBox")
        self.horizontalLayout_8.addWidget(self.generator_amplitude_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.generator_waveform_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_waveform_button.sizePolicy().hasHeightForWidth())
        self.generator_waveform_button.setSizePolicy(sizePolicy)
        self.generator_waveform_button.setMaximumSize(QtCore.QSize(220, 40))
        self.generator_waveform_button.setStyleSheet("QPushButton {\n"
"    background-color: #722f37;\n"
"    border: 1px solid #5a232a;\n"
"    color: #f5e9e2;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: 500;\n"
"    min-width: 80px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #8d2f42;\n"
"    border-color: #722f37;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #5a232a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #3d2a2e;\n"
"    border-color: #2a1a1f;\n"
"    color: #6b5d5a;\n"
"}")
        self.generator_waveform_button.setObjectName("generator_waveform_button")
        self.horizontalLayout_9.addWidget(self.generator_waveform_button)
        self.generator_waveform_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_waveform_spinBox.sizePolicy().hasHeightForWidth())
        self.generator_waveform_spinBox.setSizePolicy(sizePolicy)
        self.generator_waveform_spinBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.generator_waveform_spinBox.setStyleSheet("QSpinBox, QDoubleSpinBox {\n"
"    background-color: #3d2a2e;\n"
"    border: 1px solid #5a232a;\n"
"    border-radius: 4px;\n"
"    padding: 6px 10px;\n"
"    min-width: 80px;\n"
"    color: #f5e9e2;\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 1px solid #d4a373;\n"
"}\n"
"\n"
"")
        self.generator_waveform_spinBox.setMaximum(5)
        self.generator_waveform_spinBox.setObjectName("generator_waveform_spinBox")
        self.horizontalLayout_9.addWidget(self.generator_waveform_spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(200, 40))
        self.label_20.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.command_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.command_label.sizePolicy().hasHeightForWidth())
        self.command_label.setSizePolicy(sizePolicy)
        self.command_label.setMaximumSize(QtCore.QSize(200, 20))
        self.command_label.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.command_label.setObjectName("command_label")
        self.horizontalLayout_10.addWidget(self.command_label)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMaximumSize(QtCore.QSize(200, 40))
        self.label_21.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.response_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.response_label.sizePolicy().hasHeightForWidth())
        self.response_label.setSizePolicy(sizePolicy)
        self.response_label.setMaximumSize(QtCore.QSize(200, 20))
        self.response_label.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.response_label.setObjectName("response_label")
        self.horizontalLayout_11.addWidget(self.response_label)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 219, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_76.setContentsMargins(11, 0, 0, 0)
        self.horizontalLayout_76.setSpacing(0)
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.label_78 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_78.sizePolicy().hasHeightForWidth())
        self.label_78.setSizePolicy(sizePolicy)
        self.label_78.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("QLabel {\n"
"    color: #f5e9e2;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QLabel.title {\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #f5e9e2;\n"
"    background-color: #722f37;\n"
"    padding: 4px 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QLabel.subtitle {\n"
"    font-size: 14px;\n"
"    color: #d9cdc6;\n"
"}\n"
"\n"
"QLabel.highlight {\n"
"    color: #d4a373;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel.complementary {\n"
"    color: #6b8e7e;\n"
"}")
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_76.addWidget(self.label_78)
        self.horizontalLayout_108 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_108.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_108.setSpacing(6)
        self.horizontalLayout_108.setObjectName("horizontalLayout_108")
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("QComboBox {\n"
"    background-color: white;  /* Background color */\n"
"    color: black;             /* Text color */\n"
"    border: 2px #3daee9;   /* Border style and color */\n"
"    padding: 2px 15px 2px 5px; /* Padding */\n"
"    selection-background-color: red; /* Selected item background color */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white; /* Dropdown list background color */\n"
"    selection-background-color: blue; /* Selected item background color */\n"
"    color: black; /* Text color in the dropdown list */\n"
"}\n"
"\n"
"QComboBox::item {\n"
"    padding: 4px 8px; /* Item padding */\n"
"}\n"
"\n"
"QComboBox::item:selected {\n"
"    background-color: red; /* Selected item background color */\n"
"}")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.horizontalLayout_108.addWidget(self.comboBox_6)
        self.refres_coms = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refres_coms.sizePolicy().hasHeightForWidth())
        self.refres_coms.setSizePolicy(sizePolicy)
        self.refres_coms.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.refres_coms.setFont(font)
        self.refres_coms.setStyleSheet("QPushButton.secondary {\n"
"    background-color: transparent;\n"
"    border: 1px solid #d4a373;\n"
"    color: #d4a373;\n"
"    padding: 8px 16px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton.secondary:hover {\n"
"    background-color: rgba(212, 163, 115, 0.1);\n"
"    border-color: #e8b786;\n"
"    color: #e8b786;\n"
"}\n"
"\n"
"QPushButton.secondary:pressed {\n"
"    background-color: rgba(212, 163, 115, 0.2);\n"
"}")
        self.refres_coms.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/refresh-circular-arrow-icon-15.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refres_coms.setIcon(icon)
        self.refres_coms.setObjectName("refres_coms")
        self.horizontalLayout_108.addWidget(self.refres_coms)
        self.horizontalLayout_76.addLayout(self.horizontalLayout_108)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(240, 10, 201, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_button.sizePolicy().hasHeightForWidth())
        self.connect_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connect_button.setFont(font)
        self.connect_button.setStyleSheet("QPushButton.secondary {\n"
"    background-color: transparent;\n"
"    border: 8px solid #d4a373;\n"
"    color: #d4a373;\n"
"    padding: 8px 16px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton.secondary:hover {\n"
"    background-color: rgba(212, 163, 115, 0.1);\n"
"    border-color: #e8b786;\n"
"    color: #e8b786;\n"
"}\n"
"\n"
"QPushButton.secondary:pressed {\n"
"    background-color: rgba(212, 163, 115, 0.2);\n"
"}")
        self.connect_button.setObjectName("connect_button")
        self.x_axis_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.x_axis_checkBox.setGeometry(QtCore.QRect(240, 50, 67, 18))
        self.x_axis_checkBox.setStyleSheet("QCheckBox {\n"
"    color: #f5e9e2;  /* Text color (matches your QLabel) */\n"
"    font-size: 14px;\n"
"    spacing: 6px;    /* Space between checkbox and text */\n"
"}\n"
"\n"
"/* Default checkbox (unchecked) */\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #a58a7a;  /* Softer border (less harsh than #d9cdc6) */\n"
"    border-radius: 3px;\n"
"    background: #3a2e2a;  /* Darker background for better contrast */\n"
"}\n"
"\n"
"/* Checked state (more elegant) */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #d4a373;  /* Warm highlight color (like QLabel.highlight) */\n"
"    border: 1px solid #d4a373;\n"
"    \n"
"}\n"
"\n"
"\n"
"\n"
"/* Pressed state (click feedback) */\n"
"QCheckBox::indicator:pressed {\n"
"    background: #5c4a44;\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QCheckBox::indicator:disabled {\n"
"    border: 1px solid #6b8e7e;\n"
"    background: #3a3a3a;\n"
"}\n"
"\n"
"/* Text color when checked (optional) */\n"
"QCheckBox:checked {\n"
"    color: #f5e9e2;  /* Keep original text color or use #d4a373 */\n"
"}")
        self.x_axis_checkBox.setChecked(True)
        self.x_axis_checkBox.setObjectName("x_axis_checkBox")
        self.y_axis_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.y_axis_checkBox.setGeometry(QtCore.QRect(340, 50, 67, 18))
        self.y_axis_checkBox.setStyleSheet("QCheckBox {\n"
"    color: #f5e9e2;  /* Text color (matches your QLabel) */\n"
"    font-size: 14px;\n"
"    spacing: 6px;    /* Space between checkbox and text */\n"
"}\n"
"\n"
"/* Default checkbox (unchecked) */\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #a58a7a;  /* Softer border (less harsh than #d9cdc6) */\n"
"    border-radius: 3px;\n"
"    background: #3a2e2a;  /* Darker background for better contrast */\n"
"}\n"
"\n"
"/* Checked state (more elegant) */\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #d4a373;  /* Warm highlight color (like QLabel.highlight) */\n"
"    border: 1px solid #d4a373;\n"
"    \n"
"}\n"
"\n"
"\n"
"/* Pressed state (click feedback) */\n"
"QCheckBox::indicator:pressed {\n"
"    background: #5c4a44;\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QCheckBox::indicator:disabled {\n"
"    border: 1px solid #6b8e7e;\n"
"    background: #3a3a3a;\n"
"}\n"
"\n"
"/* Text color when checked (optional) */\n"
"QCheckBox:checked {\n"
"    color: #f5e9e2;  /* Keep original text color or use #d4a373 */\n"
"}")
        self.y_axis_checkBox.setObjectName("y_axis_checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Serial Comunication Example"))
        self.servo_flags_button.setText(_translate("MainWindow", "Read Servo Status Flags"))
        self.label_17.setText(_translate("MainWindow", "Servo Ready"))
        self.power_supply_status_label_.setText(_translate("MainWindow", "Power supply"))
        self.power_supply_button.setText(_translate("MainWindow", "Read Power Supply Voltage Levels"))
        self.positive_power_label.setText(_translate("MainWindow", "Positive supply voltage:"))
        self.negative_power_label.setText(_translate("MainWindow", "Negative supply voltage:"))
        self.read_tuning_button.setText(_translate("MainWindow", "Read Current Tunning Number"))
        self.tuning_label.setText(_translate("MainWindow", "x"))
        self.activate_tunning_number.setText(_translate("MainWindow", "Activate Current Tunning Number"))
        self.write_function_generator_frequency_button.setText(_translate("MainWindow", "Write Function Generator Frequency"))
        self.write_function_generator_amplitude_button.setText(_translate("MainWindow", "Write Function Generator Amplitude"))
        self.generator_waveform_button.setText(_translate("MainWindow", "Write Function Generator Waveform"))
        self.label_20.setText(_translate("MainWindow", "Command Send"))
        self.command_label.setText(_translate("MainWindow", "xxxxxxxxxx"))
        self.label_21.setText(_translate("MainWindow", "Command Response"))
        self.response_label.setText(_translate("MainWindow", "xxxxxxxxxx"))
        self.label_78.setText(_translate("MainWindow", "Port"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.x_axis_checkBox.setText(_translate("MainWindow", "x-axis"))
        self.y_axis_checkBox.setText(_translate("MainWindow", "y-axis"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
