# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 730)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/small_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(23, 23, 23);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 481, 251))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid rgb(180, 0, 0);\n"
"    border-top: none;\n"
"    border-radius: 4px;\n"
"    background: rgb(240, 240, 240);\n"
"    margin-top: -1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                              stop:0 rgb(255,100,100), stop:1 rgb(200,0,0));\n"
"    border: 1px solid rgb(150, 0, 0);\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    color: white;\n"
"    padding: 6px 12px;\n"
"    margin-right: 2px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                              stop:0 rgb(246,4,2), stop:1 rgb(180,0,0));\n"
"    border-color: rgb(120, 0, 0);\n"
"    margin-bottom: -1px; /* Connects with content pane */\n"
"}\n"
"\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                              stop:0 rgb(255,130,130), stop:1 rgb(220,20,20));\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-bottom: 1px solid rgb(240, 240, 240); /* Matches pane background */\n"
"}\n"
"\n"
"QTabBar::tab:first {\n"
"    margin-left: 0; /* Optional: for left-aligned tabs */\n"
"}\n"
"\n"
"QTabBar::tab:last {\n"
"    margin-right: 0; /* Optional: for right-aligned tabs */\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.standard_waveform_comboBox = QtWidgets.QComboBox(self.tab)
        self.standard_waveform_comboBox.setGeometry(QtCore.QRect(10, 10, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.standard_waveform_comboBox.sizePolicy().hasHeightForWidth())
        self.standard_waveform_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.standard_waveform_comboBox.setFont(font)
        self.standard_waveform_comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(200, 200, 200);  /* Color when an item is selected */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;  /* Background of dropdown list */\n"
"    color: black;            /* Text color of items */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgb(230, 230, 230);  /* Light gray on hover */\n"
"    color: black;                          /* Keep text black on hover */\n"
"}")
        self.standard_waveform_comboBox.setObjectName("standard_waveform_comboBox")
        self.standard_waveform_comboBox.addItem("")
        self.standard_waveform_comboBox.addItem("")
        self.standard_waveform_comboBox.addItem("")
        self.standard_waveform_comboBox.addItem("")
        self.standard_waveform_comboBox.addItem("")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 50, 181, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.voltage_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voltage_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.voltage_doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.voltage_doubleSpinBox.setFont(font)
        self.voltage_doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.voltage_doubleSpinBox.setMinimum(-10.0)
        self.voltage_doubleSpinBox.setMaximum(10.0)
        self.voltage_doubleSpinBox.setSingleStep(0.1)
        self.voltage_doubleSpinBox.setProperty("value", 5.0)
        self.voltage_doubleSpinBox.setObjectName("voltage_doubleSpinBox")
        self.verticalLayout_5.addWidget(self.voltage_doubleSpinBox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(260, 50, 181, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.waveform_frequency_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.waveform_frequency_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.waveform_frequency_doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.waveform_frequency_doubleSpinBox.setFont(font)
        self.waveform_frequency_doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.waveform_frequency_doubleSpinBox.setDecimals(4)
        self.waveform_frequency_doubleSpinBox.setMaximum(1000000000.0)
        self.waveform_frequency_doubleSpinBox.setSingleStep(10.0)
        self.waveform_frequency_doubleSpinBox.setProperty("value", 100.0)
        self.waveform_frequency_doubleSpinBox.setObjectName("waveform_frequency_doubleSpinBox")
        self.verticalLayout_6.addWidget(self.waveform_frequency_doubleSpinBox)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 110, 181, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.number_points_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_points_spinBox.sizePolicy().hasHeightForWidth())
        self.number_points_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.number_points_spinBox.setFont(font)
        self.number_points_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.number_points_spinBox.setMinimum(10)
        self.number_points_spinBox.setMaximum(1000000000)
        self.number_points_spinBox.setSingleStep(10)
        self.number_points_spinBox.setProperty("value", 1000)
        self.number_points_spinBox.setObjectName("number_points_spinBox")
        self.verticalLayout_7.addWidget(self.number_points_spinBox)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(260, 110, 181, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verticalLayoutWidget_11.setFont(font)
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_11.addWidget(self.label_14)
        self.width_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.width_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.width_doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.width_doubleSpinBox.setFont(font)
        self.width_doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.width_doubleSpinBox.setDecimals(2)
        self.width_doubleSpinBox.setMinimum(0.0)
        self.width_doubleSpinBox.setMaximum(1.0)
        self.width_doubleSpinBox.setSingleStep(0.01)
        self.width_doubleSpinBox.setProperty("value", 0.5)
        self.width_doubleSpinBox.setObjectName("width_doubleSpinBox")
        self.verticalLayout_11.addWidget(self.width_doubleSpinBox)
        self.send_to_axis_standard = QtWidgets.QPushButton(self.tab)
        self.send_to_axis_standard.setGeometry(QtCore.QRect(110, 10, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_to_axis_standard.sizePolicy().hasHeightForWidth())
        self.send_to_axis_standard.setSizePolicy(sizePolicy)
        self.send_to_axis_standard.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.send_to_axis_standard.setObjectName("send_to_axis_standard")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(10, 170, 202, 51))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.verticalLayout_13.addWidget(self.label_16)
        self.duration_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.duration_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.duration_doubleSpinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duration_doubleSpinBox.setFont(font)
        self.duration_doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.duration_doubleSpinBox.setDecimals(2)
        self.duration_doubleSpinBox.setMinimum(0.0)
        self.duration_doubleSpinBox.setMaximum(1000.0)
        self.duration_doubleSpinBox.setSingleStep(0.01)
        self.duration_doubleSpinBox.setProperty("value", 0.01)
        self.duration_doubleSpinBox.setObjectName("duration_doubleSpinBox")
        self.verticalLayout_13.addWidget(self.duration_doubleSpinBox)
        self.path_to_file_lineEdit = QtWidgets.QLineEdit(self.tab)
        self.path_to_file_lineEdit.setGeometry(QtCore.QRect(220, 21, 251, 20))
        self.path_to_file_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.path_to_file_lineEdit.setObjectName("path_to_file_lineEdit")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(380, 0, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.path_to_file_pushButton = QtWidgets.QPushButton(self.tab)
        self.path_to_file_pushButton.setGeometry(QtCore.QRect(450, 0, 21, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.path_to_file_pushButton.setFont(font)
        self.path_to_file_pushButton.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 2px 2px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 2px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 2px;\n"
"}")
        self.path_to_file_pushButton.setObjectName("path_to_file_pushButton")
        self.verticalLayoutWidget_5.raise_()
        self.verticalLayoutWidget_6.raise_()
        self.verticalLayoutWidget_7.raise_()
        self.verticalLayoutWidget_11.raise_()
        self.send_to_axis_standard.raise_()
        self.verticalLayoutWidget_13.raise_()
        self.path_to_file_lineEdit.raise_()
        self.label_9.raise_()
        self.path_to_file_pushButton.raise_()
        self.standard_waveform_comboBox.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cycloid_waveform_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.cycloid_waveform_comboBox.setGeometry(QtCore.QRect(10, 10, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cycloid_waveform_comboBox.setFont(font)
        self.cycloid_waveform_comboBox.setStyleSheet("QComboBox {\n"
"    background-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(200, 200, 200);  /* Color when an item is selected */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;  /* Background of dropdown list */\n"
"    color: black;            /* Text color of items */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgb(230, 230, 230);  /* Light gray on hover */\n"
"    color: black;                          /* Keep text black on hover */\n"
"}")
        self.cycloid_waveform_comboBox.setObjectName("cycloid_waveform_comboBox")
        self.cycloid_waveform_comboBox.addItem("")
        self.cycloid_waveform_comboBox.addItem("")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 146, 161))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(270, 50, 207, 171))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cycloid_frequency_label = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cycloid_frequency_label.setFont(font)
        self.cycloid_frequency_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.cycloid_frequency_label.setObjectName("cycloid_frequency_label")
        self.verticalLayout_10.addWidget(self.cycloid_frequency_label)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_10.addWidget(self.label_13)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(170, 50, 89, 171))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_9)
        self.doubleSpinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox.setDecimals(6)
        self.doubleSpinBox.setSingleStep(0.0001)
        self.doubleSpinBox.setProperty("value", 0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_9.addWidget(self.doubleSpinBox)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_9)
        self.doubleSpinBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_2.setDecimals(6)
        self.doubleSpinBox_2.setSingleStep(1e-05)
        self.doubleSpinBox_2.setProperty("value", 0.0008)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_2)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_9)
        self.doubleSpinBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_3.setDecimals(6)
        self.doubleSpinBox_3.setSingleStep(1e-05)
        self.doubleSpinBox_3.setProperty("value", 1e-05)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_3)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_9)
        self.doubleSpinBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.doubleSpinBox_4.setMinimum(-10.0)
        self.doubleSpinBox_4.setMaximum(10.0)
        self.doubleSpinBox_4.setSingleStep(0.1)
        self.doubleSpinBox_4.setProperty("value", 5.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_4)
        self.spinBox_2 = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.spinBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_2.setMaximum(100000000)
        self.spinBox_2.setSingleStep(100)
        self.spinBox_2.setProperty("value", 2000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_9.addWidget(self.spinBox_2)
        self.send_to_axis_cycloid = QtWidgets.QPushButton(self.tab_2)
        self.send_to_axis_cycloid.setGeometry(QtCore.QRect(110, 10, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_to_axis_cycloid.sizePolicy().hasHeightForWidth())
        self.send_to_axis_cycloid.setSizePolicy(sizePolicy)
        self.send_to_axis_cycloid.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.send_to_axis_cycloid.setObjectName("send_to_axis_cycloid")
        self.horizontalLayoutWidget_2.raise_()
        self.verticalLayoutWidget_10.raise_()
        self.verticalLayoutWidget_9.raise_()
        self.send_to_axis_cycloid.raise_()
        self.cycloid_waveform_comboBox.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 801, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plot_widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setObjectName("plot_widget")
        self.verticalLayout.addWidget(self.plot_widget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(500, 140, 151, 94))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.update_graph = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_graph.sizePolicy().hasHeightForWidth())
        self.update_graph.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update_graph.setFont(font)
        self.update_graph.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.update_graph.setObjectName("update_graph")
        self.verticalLayout_2.addWidget(self.update_graph)
        self.clear_graph = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_graph.sizePolicy().hasHeightForWidth())
        self.clear_graph.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.clear_graph.setFont(font)
        self.clear_graph.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.clear_graph.setObjectName("clear_graph")
        self.verticalLayout_2.addWidget(self.clear_graph)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(500, 60, 151, 71))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.axis_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.axis_comboBox.sizePolicy().hasHeightForWidth())
        self.axis_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.axis_comboBox.setFont(font)
        self.axis_comboBox.setStyleSheet("background-color: rgb(192,192,192);\n"
"")
        self.axis_comboBox.setObjectName("axis_comboBox")
        self.axis_comboBox.addItem("")
        self.axis_comboBox.addItem("")
        self.verticalLayout_4.addWidget(self.axis_comboBox)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_4)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(500, 240, 151, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_axis_checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.x_axis_checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.x_axis_checkBox.setChecked(True)
        self.x_axis_checkBox.setObjectName("x_axis_checkBox")
        self.horizontalLayout.addWidget(self.x_axis_checkBox)
        self.y_axis_checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.y_axis_checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.y_axis_checkBox.setChecked(True)
        self.y_axis_checkBox.setObjectName("y_axis_checkBox")
        self.horizontalLayout.addWidget(self.y_axis_checkBox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(660, 60, 151, 201))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DAQ_comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DAQ_comboBox.sizePolicy().hasHeightForWidth())
        self.DAQ_comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.DAQ_comboBox.setFont(font)
        self.DAQ_comboBox.setStyleSheet("background-color: rgb(192,192,192);\n"
"")
        self.DAQ_comboBox.setObjectName("DAQ_comboBox")
        self.DAQ_comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.DAQ_comboBox)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.sample_rate_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sample_rate_spinBox.sizePolicy().hasHeightForWidth())
        self.sample_rate_spinBox.setSizePolicy(sizePolicy)
        self.sample_rate_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sample_rate_spinBox.setMaximum(1000000000)
        self.sample_rate_spinBox.setSingleStep(100)
        self.sample_rate_spinBox.setProperty("value", 5000)
        self.sample_rate_spinBox.setObjectName("sample_rate_spinBox")
        self.verticalLayout_12.addWidget(self.sample_rate_spinBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_12)
        self.send_to_daq = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_to_daq.sizePolicy().hasHeightForWidth())
        self.send_to_daq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.send_to_daq.setFont(font)
        self.send_to_daq.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.send_to_daq.setObjectName("send_to_daq")
        self.verticalLayout_3.addWidget(self.send_to_daq)
        self.stop_daq = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_daq.sizePolicy().hasHeightForWidth())
        self.stop_daq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stop_daq.setFont(font)
        self.stop_daq.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                      stop:0 rgb(210,210,210), stop:1 rgb(170,170,170));\n"
"    border: 1px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    color: rgb(50,50,50);\n"
"    font-weight: bold;\n"
"    min-width: 80px;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(230,230,230), stop:1 rgb(190,190,190));\n"
"    border: 1px solid rgb(130,130,130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                     stop:0 rgb(150,150,150), stop:1 rgb(100,100,100));\n"
"    color: rgb(220,220,220);\n"
"    padding-top: 9px;  /* Simulates a \"pressed down\" effect */\n"
"    padding-bottom: 7px;\n"
"}")
        self.stop_daq.setObjectName("stop_daq")
        self.verticalLayout_3.addWidget(self.stop_daq)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(506, 13, 301, 41))
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/images/scanner_max.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analog Waveform Generator"))
        self.standard_waveform_comboBox.setItemText(0, _translate("MainWindow", "Sine"))
        self.standard_waveform_comboBox.setItemText(1, _translate("MainWindow", "Square"))
        self.standard_waveform_comboBox.setItemText(2, _translate("MainWindow", "Triangle"))
        self.standard_waveform_comboBox.setItemText(3, _translate("MainWindow", "Sawtooth"))
        self.standard_waveform_comboBox.setItemText(4, _translate("MainWindow", "Input text"))
        self.label.setText(_translate("MainWindow", "Voltage Amplitude (volts)"))
        self.label_2.setText(_translate("MainWindow", "Wave Freq. (Hz)"))
        self.label_3.setText(_translate("MainWindow", "# Points in one wave"))
        self.label_14.setText(_translate("MainWindow", "Width"))
        self.send_to_axis_standard.setText(_translate("MainWindow", "Send to Axis"))
        self.label_16.setText(_translate("MainWindow", "Duration(s) [#points / Sample rate]"))
        self.label_9.setText(_translate("MainWindow", "Path to file:"))
        self.path_to_file_pushButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Standard Waveform Generator"))
        self.cycloid_waveform_comboBox.setItemText(0, _translate("MainWindow", "Triangle"))
        self.cycloid_waveform_comboBox.setItemText(1, _translate("MainWindow", "Sawtooth"))
        self.label_4.setText(_translate("MainWindow", "Total waveform time (s)"))
        self.label_5.setText(_translate("MainWindow", "Time for ramp portion (s)"))
        self.label_6.setText(_translate("MainWindow", "Scanner\'s Tracking Delay"))
        self.label_7.setText(_translate("MainWindow", "Voltage Amplitude (volts)"))
        self.label_8.setText(_translate("MainWindow", "Number of points"))
        self.cycloid_frequency_label.setText(_translate("MainWindow", "Frequency "))
        self.label_10.setText(_translate("MainWindow", "Flyback Time "))
        self.label_11.setText(_translate("MainWindow", "Flyback Frequency "))
        self.label_13.setText(_translate("MainWindow", "#points = sampling rate * Total time"))
        self.send_to_axis_cycloid.setText(_translate("MainWindow", "Send to Axis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Cycloid Waveform"))
        self.update_graph.setText(_translate("MainWindow", "Update Graph"))
        self.clear_graph.setText(_translate("MainWindow", "Clear Graph"))
        self.axis_comboBox.setItemText(0, _translate("MainWindow", "X-Axis"))
        self.axis_comboBox.setItemText(1, _translate("MainWindow", "Y-Axis"))
        self.checkBox.setText(_translate("MainWindow", "Together (X-axis)"))
        self.x_axis_checkBox.setText(_translate("MainWindow", "x-axis"))
        self.y_axis_checkBox.setText(_translate("MainWindow", "y-axis"))
        self.DAQ_comboBox.setItemText(0, _translate("MainWindow", "NI DAQ"))
        self.label_15.setText(_translate("MainWindow", "Sample rate (Hz)"))
        self.send_to_daq.setText(_translate("MainWindow", "Send to DAQ"))
        self.stop_daq.setText(_translate("MainWindow", "Stop DAQ"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
